### ISSUE TITLE
Data migration issue from Canada (on-prem) to China SAP cloud

### ISSUE THREAD

**Issue by themukeshkumar** [SAP-samples/commerce-migration-toolkit#15]
Dear Team, 

We are trying to do the data migration with the help of CMT but it takes 3 hrs to **preview Data migration changes** 

We would like to understand following 

- Is this CMT already tested with data migration to the China region with the source DB outside China?
- can we get some support on this?
- Did anyone face a VPN slowness issue? 

Best Regards
Mukesh Kumar

**Comment by lnowakowski** [comment]
This repository is no longer maintained. Please refer to [sap-commerce-db-sync](https://github.com/SAP/sap-commerce-db-sync) &rarr; [How to Obtain Support](https://github.com/SAP/sap-commerce-db-sync/?tab=readme-ov-file#how-to-obtain-support)
