### ISSUE TITLE
Property not displayed correctly

### ISSUE THREAD

**Issue by stephan-beutel-sap** [SAP-samples/commerce-migration-toolkit#3]
IN HAC Migration -> Data Sources tab, the connection string is not displayed properly.

Displayed: jdbc:sap://XXX:30015/?reconnect=true&statementCacheSize=512¤tSchema=XXX

Expected: jdbc:sap://XXX:30015/?reconnect=true&statementCacheSize=512&currentSchema=XXX

**Comment by lnowakowski** [comment]
This looks more like general issue in HAC for displaying HTML entities where it should be just escaped:
![image](https://user-images.githubusercontent.com/11714311/129346728-564c5eca-6464-4485-ae4b-59fdbd65c5aa.png)
